// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: profile.sql

package db

import (
	"context"
)

const addProfile = `-- name: AddProfile :one
INSERT INTO sf_profile (
    user_id, nickname, avatar
) VALUES (
             $1, $2, $3
         ) RETURNING nickname, avatar
`

type AddProfileParams struct {
	UserID   int64  `json:"user_id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

type AddProfileRow struct {
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}

func (q *Queries) AddProfile(ctx context.Context, arg AddProfileParams) (AddProfileRow, error) {
	row := q.db.QueryRow(ctx, addProfile, arg.UserID, arg.Nickname, arg.Avatar)
	var i AddProfileRow
	err := row.Scan(&i.Nickname, &i.Avatar)
	return i, err
}
