// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package db

import (
	"context"
)

const add = `-- name: Add :one
INSERT INTO users (email, password)
VALUES ($1, $2)
    RETURNING id, email, password, created_at
`

type AddParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) Add(ctx context.Context, arg AddParams) (User, error) {
	row := q.db.QueryRow(ctx, add, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}
