@base=http://localhost:8080
@auth=/api/v1/public
@main=/api/v1/web
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQwMmRlMDVmLWE3OGItNDJiZS05ZDMwLWEzYmU5NzFmOTc4NCIsInVzZXJfaWQiOjEsInJvbGUiOjksImlzc3VlZF9hdCI6IjIwMjUtMDMtMDJUMjI6NDA6MzMuMTY4MDkzMzAzKzA3OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjUtMDMtMDNUMjI6NDA6MzMuMTY4MDkzNTg0KzA3OjAwIn0.w778pRKV1mI1frD78pTvy7U0h4Y05VqJcG_fNMl7hvk

### Login
POST {{base}}{{auth}}/login
Content-Type: application/json

{
  "username": "vanhieudev",
  "password": "123456"
}

### Get list
GET {{base}}{{main}}/questions/total?sid=2
Authorization: Bearer {{token}}