@base=http://localhost:8080
@auth=/api/v1/public
@main=/api/v1/web
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGEwYmFkLTA1YWQtNDU1OS04OWNlLWQzMWViOTY2ZWM4OSIsInVzZXJfaWQiOjUsInJvbGUiOjQsImlzc3VlZF9hdCI6IjIwMjUtMDMtMDhUMDQ6MTg6MDQuOTA5ODcxNDQ2KzA3OjAwIiwiZXhwaXJlZF9hdCI6IjIwMjUtMDMtMDlUMDQ6MTg6MDQuOTA5ODcxNzI3KzA3OjAwIn0.GEW2Zjfza8zgSP9YiKRH0X8Mr4G-0uttolzOmxpTpcg

### Login
POST {{base}}{{auth}}/login
Content-Type: application/json

{
  "username": "vanhieudev",
  "password": "123456"
}

### Get list
GET {{base}}{{main}}/questions/total?sid=1
Authorization: Bearer {{token}}